# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/gaussiansplats3d.fbs".

# You can extend this class by creating a "GaussianSplats3DExt" class in "gaussian_splats3d_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions
from .gaussian_splats3d_ext import GaussianSplats3DExt

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["GaussianSplats3D"]


@define(str=False, repr=False, init=False)
class GaussianSplats3D(GaussianSplats3DExt, Archetype, VisualizableArchetype):
    """
    **Archetype**: A batch of 3D Gaussian splats.

    Each splat is an anisotropic 3D Gaussian defined by a center position, three
    per-axis scale values (standard deviations), a rotation quaternion, a base
    opacity, and a color.

    At render time the 3D covariance matrix is reconstructed as
    `Σ = R · diag(s²) · Rᵀ`, projected into screen space via the EWA splatting
    formulation, and drawn as an alpha-blended quad whose transparency follows the
    resulting 2D Gaussian distribution.

    If your source data stores scales in log-space (common in 3DGS training),
    apply `exp()` before logging.  If opacity is stored in logit-space, apply
    `sigmoid()` before logging.
    """

    # __init__ can be found in gaussian_splats3d_ext.py

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            centers=None,
            scales=None,
            quaternions=None,
            opacities=None,
            colors=None,
        )

    @classmethod
    def _clear(cls) -> GaussianSplats3D:
        """Produce an empty GaussianSplats3D, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        centers: datatypes.Vec3DArrayLike | None = None,
        scales: datatypes.Vec3DArrayLike | None = None,
        quaternions: datatypes.QuaternionArrayLike | None = None,
        opacities: datatypes.Float32ArrayLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
    ) -> GaussianSplats3D:
        """
        Update only some specific fields of a `GaussianSplats3D`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        centers:
            Per-splat 3D center position in object (local) space.
        scales:
            Per-splat anisotropic scale (standard deviation) along each of the three
            local axes, in **linear space**.

            These correspond directly to the diagonal of the scale matrix
            `S = diag(sx, sy, sz)` used when reconstructing the 3D covariance:
            `Σ = R · S² · Rᵀ`.

            If your training framework outputs log-scales, apply `exp()` before logging.
        quaternions:
            Per-splat rotation as a unit quaternion in `(x, y, z, w)` convention.

            Defines the orientation of the splat's local frame relative to the object
            frame.  If omitted, all splats are axis-aligned (identity rotation).
        opacities:
            Per-splat base opacity in the range [0, 1].

            This is the peak alpha at the Gaussian center before the spatial falloff is
            applied.  It represents a learned physical property of the splat and is
            independent of the color alpha channel.

            If your source data stores opacity in logit-space (as is common during
            3DGS training), apply `sigmoid()` before logging.

            Defaults to `1.0` if not specified.
        colors:
            Per-splat color in linear RGBA.

            The RGB channels define the base color of the Gaussian.  The alpha channel,
            if present, acts as an additional visualization-level transparency multiplier
            applied on top of `opacities`.

            Defaults to white `(1, 1, 1, 1)` if not specified.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "centers": centers,
                "scales": scales,
                "quaternions": quaternions,
                "opacities": opacities,
                "colors": colors,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> GaussianSplats3D:
        """Clear all the fields of a `GaussianSplats3D`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        centers: datatypes.Vec3DArrayLike | None = None,
        scales: datatypes.Vec3DArrayLike | None = None,
        quaternions: datatypes.QuaternionArrayLike | None = None,
        opacities: datatypes.Float32ArrayLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        centers:
            Per-splat 3D center position in object (local) space.
        scales:
            Per-splat anisotropic scale (standard deviation) along each of the three
            local axes, in **linear space**.

            These correspond directly to the diagonal of the scale matrix
            `S = diag(sx, sy, sz)` used when reconstructing the 3D covariance:
            `Σ = R · S² · Rᵀ`.

            If your training framework outputs log-scales, apply `exp()` before logging.
        quaternions:
            Per-splat rotation as a unit quaternion in `(x, y, z, w)` convention.

            Defines the orientation of the splat's local frame relative to the object
            frame.  If omitted, all splats are axis-aligned (identity rotation).
        opacities:
            Per-splat base opacity in the range [0, 1].

            This is the peak alpha at the Gaussian center before the spatial falloff is
            applied.  It represents a learned physical property of the splat and is
            independent of the color alpha channel.

            If your source data stores opacity in logit-space (as is common during
            3DGS training), apply `sigmoid()` before logging.

            Defaults to `1.0` if not specified.
        colors:
            Per-splat color in linear RGBA.

            The RGB channels define the base color of the Gaussian.  The alpha channel,
            if present, acts as an additional visualization-level transparency multiplier
            applied on top of `opacities`.

            Defaults to white `(1, 1, 1, 1)` if not specified.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                centers=centers,
                scales=scales,
                quaternions=quaternions,
                opacities=opacities,
                colors=colors,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "GaussianSplats3D:centers": centers,
            "GaussianSplats3D:scales": scales,
            "GaussianSplats3D:quaternions": quaternions,
            "GaussianSplats3D:opacities": opacities,
            "GaussianSplats3D:colors": colors,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    centers: components.Translation3DBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.Translation3DBatch._converter,  # type: ignore[misc]
    )
    # Per-splat 3D center position in object (local) space.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    scales: components.HalfSize3DBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.HalfSize3DBatch._converter,  # type: ignore[misc]
    )
    # Per-splat anisotropic scale (standard deviation) along each of the three
    # local axes, in **linear space**.
    #
    # These correspond directly to the diagonal of the scale matrix
    # `S = diag(sx, sy, sz)` used when reconstructing the 3D covariance:
    # `Σ = R · S² · Rᵀ`.
    #
    # If your training framework outputs log-scales, apply `exp()` before logging.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    quaternions: components.RotationQuatBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.RotationQuatBatch._converter,  # type: ignore[misc]
    )
    # Per-splat rotation as a unit quaternion in `(x, y, z, w)` convention.
    #
    # Defines the orientation of the splat's local frame relative to the object
    # frame.  If omitted, all splats are axis-aligned (identity rotation).
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    opacities: components.OpacityBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.OpacityBatch._converter,  # type: ignore[misc]
    )
    # Per-splat base opacity in the range [0, 1].
    #
    # This is the peak alpha at the Gaussian center before the spatial falloff is
    # applied.  It represents a learned physical property of the splat and is
    # independent of the color alpha channel.
    #
    # If your source data stores opacity in logit-space (as is common during
    # 3DGS training), apply `sigmoid()` before logging.
    #
    # Defaults to `1.0` if not specified.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    colors: components.ColorBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ColorBatch._converter,  # type: ignore[misc]
    )
    # Per-splat color in linear RGBA.
    #
    # The RGB channels define the base color of the Gaussian.  The alpha channel,
    # if present, acts as an additional visualization-level transparency multiplier
    # applied on top of `opacities`.
    #
    # Defaults to white `(1, 1, 1, 1)` if not specified.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("GaussianSplats3D", overrides=self.as_component_batches(), mappings=mappings)
