// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/gaussiansplats3d.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A batch of 3D Gaussian splats.
///
/// Each splat is an anisotropic 3D Gaussian defined by a center position, three
/// per-axis scale values (standard deviations), a rotation quaternion, a base
/// opacity, and a color.
///
/// At render time the 3D covariance matrix is reconstructed as
/// `Σ = R · diag(s²) · Rᵀ`, projected into screen space via the EWA splatting
/// formulation, and drawn as an alpha-blended quad whose transparency follows the
/// resulting 2D Gaussian distribution.
///
/// If your source data stores scales in log-space (common in 3DGS training),
/// apply `exp()` before logging.  If opacity is stored in logit-space, apply
/// `sigmoid()` before logging.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct GaussianSplats3D {
    /// Per-splat 3D center position in object (local) space.
    pub centers: Option<SerializedComponentBatch>,

    /// Per-splat anisotropic scale (standard deviation) along each of the three
    /// local axes, in **linear space**.
    ///
    /// These correspond directly to the diagonal of the scale matrix
    /// `S = diag(sx, sy, sz)` used when reconstructing the 3D covariance:
    /// `Σ = R · S² · Rᵀ`.
    ///
    /// If your training framework outputs log-scales, apply `exp()` before logging.
    pub scales: Option<SerializedComponentBatch>,

    /// Per-splat rotation as a unit quaternion in `(x, y, z, w)` convention.
    ///
    /// Defines the orientation of the splat's local frame relative to the object
    /// frame.  If omitted, all splats are axis-aligned (identity rotation).
    pub quaternions: Option<SerializedComponentBatch>,

    /// Per-splat base opacity in the range [0, 1].
    ///
    /// This is the peak alpha at the Gaussian center before the spatial falloff is
    /// applied.  It represents a learned physical property of the splat and is
    /// independent of the color alpha channel.
    ///
    /// If your source data stores opacity in logit-space (as is common during
    /// 3DGS training), apply `sigmoid()` before logging.
    ///
    /// Defaults to `1.0` if not specified.
    pub opacities: Option<SerializedComponentBatch>,

    /// Per-splat color in linear RGBA.
    ///
    /// The RGB channels define the base color of the Gaussian.  The alpha channel,
    /// if present, acts as an additional visualization-level transparency multiplier
    /// applied on top of `opacities`.
    ///
    /// Defaults to white `(1, 1, 1, 1)` if not specified.
    pub colors: Option<SerializedComponentBatch>,
}

impl GaussianSplats3D {
    /// Returns the [`ComponentDescriptor`] for [`Self::centers`].
    ///
    /// The corresponding component is [`crate::components::Translation3D`].
    #[inline]
    pub fn descriptor_centers() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.GaussianSplats3D".into()),
            component: "GaussianSplats3D:centers".into(),
            component_type: Some("rerun.components.Translation3D".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::scales`].
    ///
    /// The corresponding component is [`crate::components::HalfSize3D`].
    #[inline]
    pub fn descriptor_scales() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.GaussianSplats3D".into()),
            component: "GaussianSplats3D:scales".into(),
            component_type: Some("rerun.components.HalfSize3D".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::quaternions`].
    ///
    /// The corresponding component is [`crate::components::RotationQuat`].
    #[inline]
    pub fn descriptor_quaternions() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.GaussianSplats3D".into()),
            component: "GaussianSplats3D:quaternions".into(),
            component_type: Some("rerun.components.RotationQuat".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::opacities`].
    ///
    /// The corresponding component is [`crate::components::Opacity`].
    #[inline]
    pub fn descriptor_opacities() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.GaussianSplats3D".into()),
            component: "GaussianSplats3D:opacities".into(),
            component_type: Some("rerun.components.Opacity".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::colors`].
    ///
    /// The corresponding component is [`crate::components::Color`].
    #[inline]
    pub fn descriptor_colors() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.GaussianSplats3D".into()),
            component: "GaussianSplats3D:colors".into(),
            component_type: Some("rerun.components.Color".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            GaussianSplats3D::descriptor_centers(),
            GaussianSplats3D::descriptor_scales(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            GaussianSplats3D::descriptor_quaternions(),
            GaussianSplats3D::descriptor_opacities(),
            GaussianSplats3D::descriptor_colors(),
        ]
    });

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 5usize]> =
    std::sync::LazyLock::new(|| {
        [
            GaussianSplats3D::descriptor_centers(),
            GaussianSplats3D::descriptor_scales(),
            GaussianSplats3D::descriptor_quaternions(),
            GaussianSplats3D::descriptor_opacities(),
            GaussianSplats3D::descriptor_colors(),
        ]
    });

impl GaussianSplats3D {
    /// The total number of components in the archetype: 2 required, 3 recommended, 0 optional
    pub const NUM_COMPONENTS: usize = 5usize;
}

impl ::re_types_core::Archetype for GaussianSplats3D {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.GaussianSplats3D".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Gaussian splats 3D"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let centers = arrays_by_descr
            .get(&Self::descriptor_centers())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_centers()));
        let scales = arrays_by_descr
            .get(&Self::descriptor_scales())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_scales()));
        let quaternions = arrays_by_descr
            .get(&Self::descriptor_quaternions())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_quaternions())
            });
        let opacities = arrays_by_descr
            .get(&Self::descriptor_opacities())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_opacities())
            });
        let colors = arrays_by_descr
            .get(&Self::descriptor_colors())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_colors()));
        Ok(Self {
            centers,
            scales,
            quaternions,
            opacities,
            colors,
        })
    }
}

impl ::re_types_core::AsComponents for GaussianSplats3D {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.centers.clone(),
            self.scales.clone(),
            self.quaternions.clone(),
            self.opacities.clone(),
            self.colors.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for GaussianSplats3D {}

impl crate::VisualizableArchetype for GaussianSplats3D {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("GaussianSplats3D").with_overrides(self)
    }
}

impl GaussianSplats3D {
    /// Create a new `GaussianSplats3D`.
    #[inline]
    pub(crate) fn new(
        centers: impl IntoIterator<Item = impl Into<crate::components::Translation3D>>,
        scales: impl IntoIterator<Item = impl Into<crate::components::HalfSize3D>>,
    ) -> Self {
        Self {
            centers: try_serialize_field(Self::descriptor_centers(), centers),
            scales: try_serialize_field(Self::descriptor_scales(), scales),
            quaternions: None,
            opacities: None,
            colors: None,
        }
    }

    /// Update only some specific fields of a `GaussianSplats3D`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `GaussianSplats3D`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            centers: Some(SerializedComponentBatch::new(
                crate::components::Translation3D::arrow_empty(),
                Self::descriptor_centers(),
            )),
            scales: Some(SerializedComponentBatch::new(
                crate::components::HalfSize3D::arrow_empty(),
                Self::descriptor_scales(),
            )),
            quaternions: Some(SerializedComponentBatch::new(
                crate::components::RotationQuat::arrow_empty(),
                Self::descriptor_quaternions(),
            )),
            opacities: Some(SerializedComponentBatch::new(
                crate::components::Opacity::arrow_empty(),
                Self::descriptor_opacities(),
            )),
            colors: Some(SerializedComponentBatch::new(
                crate::components::Color::arrow_empty(),
                Self::descriptor_colors(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.centers
                .map(|centers| centers.partitioned(_lengths.clone()))
                .transpose()?,
            self.scales
                .map(|scales| scales.partitioned(_lengths.clone()))
                .transpose()?,
            self.quaternions
                .map(|quaternions| quaternions.partitioned(_lengths.clone()))
                .transpose()?,
            self.opacities
                .map(|opacities| opacities.partitioned(_lengths.clone()))
                .transpose()?,
            self.colors
                .map(|colors| colors.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_centers = self.centers.as_ref().map(|b| b.array.len());
        let len_scales = self.scales.as_ref().map(|b| b.array.len());
        let len_quaternions = self.quaternions.as_ref().map(|b| b.array.len());
        let len_opacities = self.opacities.as_ref().map(|b| b.array.len());
        let len_colors = self.colors.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_centers)
            .or(len_scales)
            .or(len_quaternions)
            .or(len_opacities)
            .or(len_colors)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Per-splat 3D center position in object (local) space.
    #[inline]
    pub fn with_centers(
        mut self,
        centers: impl IntoIterator<Item = impl Into<crate::components::Translation3D>>,
    ) -> Self {
        self.centers = try_serialize_field(Self::descriptor_centers(), centers);
        self
    }

    /// Per-splat anisotropic scale (standard deviation) along each of the three
    /// local axes, in **linear space**.
    ///
    /// These correspond directly to the diagonal of the scale matrix
    /// `S = diag(sx, sy, sz)` used when reconstructing the 3D covariance:
    /// `Σ = R · S² · Rᵀ`.
    ///
    /// If your training framework outputs log-scales, apply `exp()` before logging.
    #[inline]
    pub fn with_scales(
        mut self,
        scales: impl IntoIterator<Item = impl Into<crate::components::HalfSize3D>>,
    ) -> Self {
        self.scales = try_serialize_field(Self::descriptor_scales(), scales);
        self
    }

    /// Per-splat rotation as a unit quaternion in `(x, y, z, w)` convention.
    ///
    /// Defines the orientation of the splat's local frame relative to the object
    /// frame.  If omitted, all splats are axis-aligned (identity rotation).
    #[inline]
    pub fn with_quaternions(
        mut self,
        quaternions: impl IntoIterator<Item = impl Into<crate::components::RotationQuat>>,
    ) -> Self {
        self.quaternions = try_serialize_field(Self::descriptor_quaternions(), quaternions);
        self
    }

    /// Per-splat base opacity in the range [0, 1].
    ///
    /// This is the peak alpha at the Gaussian center before the spatial falloff is
    /// applied.  It represents a learned physical property of the splat and is
    /// independent of the color alpha channel.
    ///
    /// If your source data stores opacity in logit-space (as is common during
    /// 3DGS training), apply `sigmoid()` before logging.
    ///
    /// Defaults to `1.0` if not specified.
    #[inline]
    pub fn with_opacities(
        mut self,
        opacities: impl IntoIterator<Item = impl Into<crate::components::Opacity>>,
    ) -> Self {
        self.opacities = try_serialize_field(Self::descriptor_opacities(), opacities);
        self
    }

    /// Per-splat color in linear RGBA.
    ///
    /// The RGB channels define the base color of the Gaussian.  The alpha channel,
    /// if present, acts as an additional visualization-level transparency multiplier
    /// applied on top of `opacities`.
    ///
    /// Defaults to white `(1, 1, 1, 1)` if not specified.
    #[inline]
    pub fn with_colors(
        mut self,
        colors: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        self.colors = try_serialize_field(Self::descriptor_colors(), colors);
        self
    }
}

impl ::re_byte_size::SizeBytes for GaussianSplats3D {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.centers.heap_size_bytes()
            + self.scales.heap_size_bytes()
            + self.quaternions.heap_size_bytes()
            + self.opacities.heap_size_bytes()
            + self.colors.heap_size_bytes()
    }
}
